<?php
Class Elements
{
public $buy = array();
public $rent = array();
public function __construct() {
	
$this->buy['Residential']['Residential'] = $this->rent['Residential']['Rental'] =array(
'House',
'Unit',
'Townhouse',
'Villa',
'Apartment',
'Flat',
'Studio',
'Warehouse',
'Alpine',
'Retirement',
'BlockOfUnits',
'Other',
'DuplexSemi-detached',
'AcreageSemi-rural',
'Terrace',
'ServicedApartment'
);

$this->buy['Residential']['Rural'] = array(
'Cropping',
'Dairy',
'Farmlet',
'Horticulture',
'Livestock',
'Viticulture',
'MixedFarming',
'Lifestyle',
'Other');
$this->buy['Residential']['Land'] = $this->buy['Commercial']['CommercialLand'] = array();
$this->rent['Residential']['Holiday'] = array(
'Alpine',
'Apartment',
'BackpackerHostel',
'BedAndBreakfast',
'Campground',
'CaravanHolidayPark',
'DuplexSemi-detached',
'ExecutiveRental',
'FarmStay',
'Flat',
'Hotel',
'House',
'HouseBoat',
'Lodge',
'Motel',
'Resort',
'Retreat',
'SelfContainedCottage',
'ServicedApartment',
'Studio',
'Terrace',
'Townhouse',
'Unit',
'Villa',
'Other');

$this->buy['Commercial']['Commercial'] = array(
'Commercial Farming',
'Land/Development',
'Hotel/Leisure',
'Industrial/Warehouse',
'Medical/Consulting',
'Offices',
'Retail',
'Showrooms/Bulky Goods'
);

$this->buy['Business'] = $lease['Business']= array(
'Accommodation/Tourism' => array(
         'Aged Care',
         'Backpacker/Hostel',
         'Boarding Kennels',
         'Caravan Park',
         'Function Centre',
         'Guest House/B&B',
         'Hotel',
         'Management Rights',
         'Motel',
         'Resort',
         'Retirement Village',
         'Theme Park',
         'Tours'),
    'Automotive'=> array(
         'Accessories/Parts',
         'Aeronautical',
         'Auto Electrical',
         'Bike and Motorcycle',
         'Car Dealership',
         'Car Rental',
         'Car Wash',
         'Detailing',
         'Driving Schools',
         'Marine',
         'Mechanical Repair',
         'Panel Beating',
         'Service Station',
         'Truck',
         'Wreckers'),
    'Beauty/Health' => array(
         'Beauty Products',
         'Beauty Salon',
         'Dental',
         'Hair',
         'Hospital',
         'Medical',
         'Nails',
         'Nursing Home',
         'Massage',
         'Health Spa',
         'Medical Practice',
         'Natural Therapies',
         'Recreation/Sport'),
    'Education/Training' => array(
         'Child Care',
         'Employment/Recruitment',
         'Educational',
         'Training'),
    'Food/Hospitality' => array(
         'Alcohol/Liquor',
         'Bakery',
         'Butcher',
         'Cafe/Coffee Shop',
         'Catering',
         'Convenience Store',
         'Deli',
         'Distributors',
         'Fruit/Veg',
         'Juice Bar',
         'Manufacturers',
         'Restaurant',
         'Retailer',
         'Supermarket',
         'Takeaway Food',
         'Wholesalers'),
    'Franchise' => 'Franchise',
    'Home/Garden' => array(
         'Home Based',
         'Homewares/Hardware',
         'Irrigation Services',
         'Gardening',
         'Nursery'),
    'Import/Export/Whole' => array(
         'Freight',
         'Customs',
         'Import',
         'Export',
         'Wholesale'),
    'Industrial/Manufacturing' => array(
         'Building and Construction',
         'Civil',
         'Clothing/Footwear',
         'Electrical',
         'Food/Beverage',
         'Furniture/Timber',
         'Glass/Ceramic',
         'Machinery/Metal',
         'Manufacturing/Engineering',
         'Mining/Earth Moving',
         'Oil/Gas',
         'Paper/Printing',
         'Plastic',
         'Water',
         'Welding'),
    'Leisure/Entertainment' => array(
         'Adult',
         'Aircraft',
         'Amusements',
         'Aquatic/Marine',
         'Arts/Crafts',
         'Bars/Nightclubs',
         'Function Centre',
         'Gambling',
         'Garden/Nurseries',
         'Hotel',
         'Music/Video',
         'Recreation/Sport',
         'Sports Complex/Gym',
         'Vending'),
    'Professional' => array(
         'Accounting',
         'Advertising/Mkting',
         'Bookkeeping',
         'Brokerage',
         'Civil',
         'Communications',
         'Computer/IT',
         'Finance',
         'Insurance',
         'Internet',
         'Legal',
         'Media',
         'Medical',
         'Property/Real Estate',
         'Recruitment',
         'Scientific',
         'Security',
         'Travel'),
    'Retail' => array(
         'Clothing/Accessories',
         'Entertainment/Tech',
         'Florist/Nursery',
         'Food/Beverage',
         'Health/Beauty',
         'Homeware/Hardware',
         'Newsagency/Tatts',
         'Office Supplies',
         'Animal related',
         'Pharmacies',
         'Post Offices',
         'Vending'),
    'Rural' => array(
         'Aerial',
         'Agricultural',
         'Aquaculture',
         'Crop Harvesting',
         'Dairy Farming',
         'Farming',
         'Fertiliser',
         'Fishing/Forestry',
         'Fruit Picking',
         'Hunting/Trap',
         'Insemination',
         'Irrigation Services',
         'Land Clearing',
         'Livestock',
         'Machinery',
         'Mustering',
         'Shearing',
         'Wool Classing'),
    'Services' => array(
         'Aircraft',
         'Alarms',
         'Animal related',
         'Boats/Marine',
         'Car/Bus/Truck',
         'Cleaning',
         'Communication',
         'Copy/Laminate',
         'Courier',
         'Driving Schools',
         'Entertainment',
         'Garden/Household',
         'Hire/Rent',
         'Limousine/Taxi',
         'Machinery',
         'Management Rights',
         'Medical',
         'Mobile Services',
         'Pest related',
         'Pool/Water',
         'Print/Photo',
         'Repair'),
    'Transport/Distribution' => array(
         'Air',
         'Bus',
         'Car',
         'Parking',
         'Rail',
         'Road',
         'Sea',
         'Taxi',
         'Truck'));
	 }
}
?>